---
title: "04_figures_R"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(Seurat)
```


## Load dataset

CSC combined generated in [01_prepare_scrnaseq_data](01_prepare_scrnaseq_data.md).
Enterocyte subset is generated in [02_Seurat_processing](02_Seurat_processing.md).

```{r cars}
load(file = "./raw_data/csc.combined_seurat.Rda")
load(file = "./raw_data/entcrypt.subset.filt.Rda")

```

##Plot marker genes for enterocyte cluster election
Figure S1C
```{r 01}
FeaturePlot(object = csc.combined, features.plot = c("Mki67","Alpi","Muc2","Cck"), cols.use = c("grey", "blue"), 
            reduction.use = "tsne")
ggsave(file="./figures/supplement/FigS1C_tsne_marker_genes.pdf",plot=last_plot(),width=6.5,height=6)

```

## Add zonation reconstruction for plotting
```{r 02}
zone_table<-read.delim(file="./raw_data/cell_zone_table.txt",header = T)
rownames(zone_table)<-zone_table$cell_id

temp <- AddMetaData(entcrypt.subset.filt, select(zone_table,zone)) 
temp<-temp@meta.data%>%mutate(cell_id=rownames(.),zone_all=ifelse(is.na(zone),0,zone))   #set zone of crypt cells to 0, they did not undergo zonation reconstruction.

rownames(temp)<-temp$cell_id
new <- AddMetaData(entcrypt.subset.filt, select(temp,zone_all))
FeaturePlot(object = new, features.plot = c("zone_all"), cols.use = c("blue","yellow"), pt.size=2,no.legend = F,
            reduction.use = "tsne")

ggsave(file="./figures/main/Fig2D_tsne_reconstruction.pdf",plot=last_plot(),width=6.5,height=6)

```

## Expression plots

```{r 03}
FeaturePlot(object = entcrypt.subset.filt, features.plot = c("Ada","Slc28a2","Nt5e"),nCol = 3, pt.size = 2, cols.use = c("grey", "blue"), 
            reduction.use = "tsne")
ggsave(file="./figures/main/Fig6C_tsne_tip_genes.pdf",plot=last_plot(),width=12,height=4)

FeaturePlot(object = entcrypt.subset.filt, features.plot = c("Rpl4","Rpl3","Cps1","Reg3g","Reg1","Gstm3","Enpep","Pigr","Slc5a1","Apoa1","Apob","Neat1","Malat1","Ada","Nt5e"),nCol = 5, cols.use = c("grey", "blue"), 
            reduction.use = "tsne")
ggsave(file="./figures/supplement/FigS2F_tsnes_supp.pdf",plot=last_plot(),width=12,height=7)

```


```{r 04}
#remove crypt clusters
noncrypt <- SubsetData(object = entcrypt.subset.filt, ident.use = c("enterocyte_1", "enterocyte_2","enterocyte_3","enterocyte_4","enterocyte_5","enterocyte_6"))


#identify all genes that are expressed in more than 10 enterocytes
genes.use <- rownames(noncrypt@data)

num.cells <- rowSums(noncrypt@data > 0)
genes.use <- names(num.cells[which(num.cells >= 10)])


#set all cluster ids identical to perform average expression function
current.cluster.ids <- c("enterocyte_1", "enterocyte_2","enterocyte_3","enterocyte_4","enterocyte_5","enterocyte_6")
new.cluster.ids <- c("all","all","all","all","all","all")
noncrypt@ident <- plyr::mapvalues(x = noncrypt@ident, from = current.cluster.ids, to = new.cluster.ids)

expression<-AverageExpression(noncrypt)
expression$gene<-rownames(expression)

#landmark genes 

bottom_landmark<-c("2010107E04Rik", "2210407C18Rik", "Atp5a1", "Atp5e", "Atp5g3", "Atp5h", "Atp5j",
                   "Atp5j2", "Atp5l", "Atp5o", "Atpif1", "Ccl25", "Chchd10", "Ckmt1", "Cox4i1", "Cox5a",
                   "Cox5b", "Cox6b1", "Cox6c", "Cox7a1", "Cox7a2", "Cox7b", "Fabp1", "Gpx2", "Gsta1", "Lgals4", 
                   "Lypd8", "Minos1", "Ndufa1", "Ndufa4", "Ndufa5", "Ndufb6", "Ndufb8", "Ndufc1", "Plac8", "Reg3b", 
                   "Reg3g", "Rpl18", "Rpl35a", "Rpl38", "Rpl39", "Rpl41", "Rplp1", "Rps12", "Rps14", "Rps18", "Rps2", 
                  "Rps27", "Rps27l", "Rps28", "Rps29", "Rps8", "Sis", "Spink4", "Tm4sf5", "Tma7",
                   "Txn1", "Uba52", "Uqcr10", "Uqcr11", "Uqcrh", "Uqcrq")


top_landmark<-c("2010109I03Rik", "Acad9", "Ada", "Ap1g1", "Apoa4", "Apoc3", "Cep57", "Cfap20", "Chchd1",
                "Chek2", "Clca4a", "Cldn7", "Fgd4", "Gcn1l1", "Glipr1", "Gm10680", "Gm20594", "Ifrd1",
                "Krt20", "Lgals3", "Lrrc41", "Mrpl48", "Myo7a", "Olfr1385", "Olfr46", "Pam", "Pkib", "Pmp22",
                "Psma7", "Rab34", "S100a10", "S100a6", "Serpinb1a", "Slc17a5", "Slc25a22", "Slc28a2", "Sprr2a2",
                "Ssbp2", "Tbk1", "Tlr1", "Tmsb4x", "Ythdc2", "Zfp280d")


filt_bottom<-intersect(bottom_landmark,genes.use)%>%
  as.data.frame()
colnames(filt_bottom)<-"gene"
bottom_join<-inner_join(filt_bottom,expression)%>%
  arrange(desc(all))
bottom<-as.character(bottom_join$gene)


filt_top<-intersect(top_landmark,genes.use)%>%
  as.data.frame()
colnames(filt_top)<-"gene"
top_join<-inner_join(filt_top,expression)%>%
  arrange(desc(all))
top<-as.character(top_join$gene)


FeaturePlot(object = noncrypt, features.plot = bottom, nCol = 6, cols.use = c("grey", "blue"), 
            reduction.use = "tsne",no.legend = T,no.axes = T,pt.size = 0.5)
ggsave(file="./figures/supplement/FigS1F_tsne_landmark_bottom.pdf",plot=last_plot(),width=7,height=11)


FeaturePlot(object = noncrypt, features.plot = top, nCol = 4, cols.use = c("grey", "blue"), 
            reduction.use = "tsne",no.legend = T,no.axes = T,pt.size = 0.5)
ggsave(file="./figures/supplement/FigS1G_tsne_landmark_tip.pdf",plot=last_plot(),width=5.3,height=9)

```

## Produce supplementary datasets
```{r 05}
library(data.table)
all_cells<-entcrypt.subset.filt@raw.data@Dimnames[[2]]
used_cells<-entcrypt.subset.filt@data@Dimnames[[2]]
int<-data.table(csc.combined@raw.data)
overlap<-all_cells %in% used_cells
mat <- data.table(as.matrix(csc.combined@raw.data))
dim(mat)
mat_filtered<-mat[, overlap, with=FALSE]
dim(mat_filtered)

genes<-entcrypt.subset.filt@data@Dimnames[[1]]


tsne<-data.frame(entcrypt.subset.filt@dr$tsne@cell.embeddings)
setDT(tsne, keep.rownames = TRUE)[]
ident<-data.frame(entcrypt.subset.filt@ident)
setDT(ident, keep.rownames = TRUE)[]
df<-dplyr::inner_join(tsne,ident,by="rn")
df_ordered<-df[match(colnames(mat_filtered),df$rn),]

cell_ids<-entcrypt.subset.filt@data@Dimnames[[2]]
str(cell_ids)
mat_export<-mat_filtered
colnames(mat_export)<-cell_ids
row.names(mat_export)<-genes
mat_export$gene<-genes
mat_export <- mat_export[, c(1384, 1:1383)]
write.table(mat_export,file="./tables/scRNAseq_UMI_table.tsv",row.names = F,quote = F,sep="\t")

tsne_export<-df_ordered
colnames(tsne_export)<-c("cell_id","tSNE_coordinate_1","tSNE_coordinate_2","cluster_id")
tsne_export_new<-left_join(tsne_export,zone_table)%>%select(-4)
lookup_table<-data.table(zone=c(1,2,3,4,5,6,NA),new_id=c("V1","V2","V3","V4","V5","V6","Crypt"))
tsne_export_new_updated<-left_join(tsne_export_new,lookup_table)%>%select(-4)%>%rename("zone"="new_id")
write.table(tsne_export_new_updated,file="./tables/scRNAseq_tsne_coordinates_zones.tsv",row.names = F,quote = F,sep="\t")

```

```{r 06}
sessionInfo()

```

